docs:
    name: Documenter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs docs/addnursery.jl
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      #  env:
      #    JULIA_PKG_SERVER: ""      
      # - run: |
      #     julia --project=docs -e '
      #       using Documenter: doctest
      #       using MYPACKAGE
      #       doctest(MYPACKAGE)'
      - run: julia --project=docs docs/make.jl
        env:
          PYTHON: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
